### ISSUE TITLE
Error in Random Sample Data Fed to PointNet

### ISSUE THREAD

**Issue by chaidosa** [vanhalen42/SCARP#2]
https://github.com/vanhalen42/SCARP/blob/398f73c52fd8015e2dc7f7d596e46924fde45b8d/models/pointnet2/pointnet.py#L42

Suggested fix: ` x = torch.rand((32,3, 2048)) `

I understand that this error may not be critical for those intending to execute SCARP. However, I believe it is still an important issue for individuals who are simply attempting to experiment with PointNet using your code.

**Comment by vanhalen42** [comment]
Thanks a lot! Will fix it.
